package com.github.yohannestz.iconsax_compose.iconsax
object IconsaxOutline {
    val Aave by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Aave }
    val Activity by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Activity }
    val Add by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Add }
    val AddCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.AddCircle }
    val AddSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.AddSquare }
    val Additem by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Additem }
    val Airdrop by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Airdrop }
    val Airplane by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Airplane }
    val AirplaneSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.AirplaneSquare }
    val Airpod by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Airpod }
    val Airpods by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Airpods }
    val Alarm by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Alarm }
    val AlignBottom by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.AlignBottom }
    val AlignHorizontally by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.AlignHorizontally }
    val AlignLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.AlignLeft }
    val AlignRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.AlignRight }
    val AlignTop by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.AlignTop }
    val AlignVertically by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.AlignVertically }
    val Android by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Android }
    val Ankr by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Ankr }
    val Apple by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Apple }
    val Aquarius by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Aquarius }
    val Archive by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Archive }
    val ArchiveAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArchiveAdd }
    val ArchiveBook by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArchiveBook }
    val ArchiveBox by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArchiveBox }
    val ArchiveMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArchiveMinus }
    val ArchiveSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArchiveSlash }
    val ArchiveTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArchiveTick }
    val ArrangeHorizontal by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrangeHorizontal }
    val ArrangeHorizontalCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrangeHorizontalCircle }
    val ArrangeHorizontalSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrangeHorizontalSquare }
    val ArrangeVertical by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrangeVertical }
    val ArrangeVerticalCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrangeVerticalCircle }
    val ArrangeVerticalSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrangeVerticalSquare }
    val Arrow by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Arrow }
    val ArrowCircleDown by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowCircleDown }
    val ArrowCircleDownTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowCircleDownTwo }
    val ArrowCircleLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowCircleLeft }
    val ArrowCircleLeftTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowCircleLeftTwo }
    val ArrowCircleRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowCircleRight }
    val ArrowCircleRightTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowCircleRightTwo }
    val ArrowCircleUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowCircleUp }
    val ArrowCircleUpTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowCircleUpTwo }
    val ArrowDown by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowDown }
    val ArrowDownThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowDownThree }
    val ArrowDownTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowDownTwo }
    val ArrowForward by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowForward }
    val ArrowForwardSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowForwardSquare }
    val ArrowLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowLeft }
    val ArrowLeftThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowLeftThree }
    val ArrowLeftTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowLeftTwo }
    val ArrowRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowRight }
    val ArrowRightThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowRightThree }
    val ArrowRightTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowRightTwo }
    val ArrowRotateLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowRotateLeft }
    val ArrowRotateRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowRotateRight }
    val ArrowSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowSquare }
    val ArrowSquareDown by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowSquareDown }
    val ArrowSquareLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowSquareLeft }
    val ArrowSquareRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowSquareRight }
    val ArrowSquareUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowSquareUp }
    val ArrowSwapHorizontal by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowSwapHorizontal }
    val ArrowSwapVertical by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowSwapVertical }
    val ArrowUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowUp }
    val ArrowUpThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowUpThree }
    val ArrowUpTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ArrowUpTwo }
    val AttachCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.AttachCircle }
    val AttachSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.AttachSquare }
    val AudioSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.AudioSquare }
    val Augur by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Augur }
    val Autobrightness by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Autobrightness }
    val Autonio by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Autonio }
    val Avalanche by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Avalanche }
    val Award by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Award }
    val Back by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Back }
    val BackSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BackSquare }
    val Backward by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Backward }
    val BackwardFifteenSeconds by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BackwardFifteenSeconds }
    val BackwardFiveSeconds by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BackwardFiveSeconds }
    val BackwardItem by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BackwardItem }
    val BackwardTenSeconds by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BackwardTenSeconds }
    val Bag by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Bag }
    val BagCross by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BagCross }
    val BagCrossOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BagCrossOne }
    val BagHappy by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BagHappy }
    val BagTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BagTick }
    val BagTickTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BagTickTwo }
    val BagTimer by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BagTimer }
    val BagTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BagTwo }
    val Bank by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Bank }
    val Barcode by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Barcode }
    val BatteryCharging by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BatteryCharging }
    val BatteryDisable by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BatteryDisable }
    val BatteryEmpty by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BatteryEmpty }
    val BatteryEmptyOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BatteryEmptyOne }
    val BatteryFull by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BatteryFull }
    val Be by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Be }
    val Bezier by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Bezier }
    val Bill by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Bill }
    val BinanceCoin by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BinanceCoin }
    val BinanceUsd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BinanceUsd }
    val Bitcoin by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Bitcoin }
    val BitcoinCard by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BitcoinCard }
    val BitcoinConvert by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BitcoinConvert }
    val BitcoinRefresh by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BitcoinRefresh }
    val Blend by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Blend }
    val BlendTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BlendTwo }
    val Blogger by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Blogger }
    val Bluetooth by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Bluetooth }
    val BluetoothCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BluetoothCircle }
    val BluetoothRectangle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BluetoothRectangle }
    val BluetoothTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BluetoothTwo }
    val Blur by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Blur }
    val Book by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Book }
    val BookOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BookOne }
    val BookSaved by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BookSaved }
    val BookSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BookSquare }
    val Bookmark by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Bookmark }
    val BookmarkTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BookmarkTwo }
    val Bootstrap by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Bootstrap }
    val Box by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Box }
    val BoxAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BoxAdd }
    val BoxOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BoxOne }
    val BoxRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BoxRemove }
    val BoxSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BoxSearch }
    val BoxTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BoxTick }
    val BoxTime by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BoxTime }
    val BoxTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BoxTwo }
    val Briefcase by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Briefcase }
    val BrifecaseCross by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BrifecaseCross }
    val BrifecaseTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BrifecaseTick }
    val BrifecaseTimer by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BrifecaseTimer }
    val Brodcast by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Brodcast }
    val Broom by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Broom }
    val Brush by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Brush }
    val BrushBig by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BrushBig }
    val BrushSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BrushSquare }
    val BrushThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BrushThree }
    val BrushTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BrushTwo }
    val Bubble by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Bubble }
    val Bucket by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Bucket }
    val BucketCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BucketCircle }
    val BucketSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BucketSquare }
    val Building by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Building }
    val BuildingFour by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BuildingFour }
    val BuildingThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BuildingThree }
    val Buildings by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Buildings }
    val BuildingsTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BuildingsTwo }
    val Buliding by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Buliding }
    val Bus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Bus }
    val BuyCrypto by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.BuyCrypto }
    val Cake by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Cake }
    val Calculator by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Calculator }
    val Calendar by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Calendar }
    val CalendarAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CalendarAdd }
    val CalendarCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CalendarCircle }
    val CalendarEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CalendarEdit }
    val CalendarOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CalendarOne }
    val CalendarRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CalendarRemove }
    val CalendarSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CalendarSearch }
    val CalendarTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CalendarTick }
    val CalendarTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CalendarTwo }
    val Call by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Call }
    val CallAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CallAdd }
    val CallCalling by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CallCalling }
    val CallIncoming by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CallIncoming }
    val CallMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CallMinus }
    val CallOutgoing by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CallOutgoing }
    val CallReceived by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CallReceived }
    val CallRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CallRemove }
    val CallSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CallSlash }
    val Camera by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Camera }
    val CameraSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CameraSlash }
    val Candle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Candle }
    val CandleTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CandleTwo }
    val Car by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Car }
    val Card by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Card }
    val CardAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CardAdd }
    val CardCoin by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CardCoin }
    val CardEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CardEdit }
    val CardPos by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CardPos }
    val CardReceive by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CardReceive }
    val CardRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CardRemove }
    val CardRemoveOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CardRemoveOne }
    val CardSend by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CardSend }
    val CardSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CardSlash }
    val CardTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CardTick }
    val CardTickOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CardTickOne }
    val Cardano by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Cardano }
    val Cards by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Cards }
    val Category by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Category }
    val CategoryTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CategoryTwo }
    val Cd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Cd }
    val Celo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Celo }
    val Celsius by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Celsius }
    val Chainlink by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Chainlink }
    val Chart by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Chart }
    val ChartCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ChartCircle }
    val ChartFail by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ChartFail }
    val ChartOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ChartOne }
    val ChartSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ChartSquare }
    val ChartSuccess by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ChartSuccess }
    val ChartTwentyOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ChartTwentyOne }
    val ChartTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ChartTwo }
    val Check by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Check }
    val ChemicalGlass by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ChemicalGlass }
    val Chrome by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Chrome }
    val Civic by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Civic }
    val Clipboard by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Clipboard }
    val ClipboardClose by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ClipboardClose }
    val ClipboardExport by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ClipboardExport }
    val ClipboardImport by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ClipboardImport }
    val ClipboardText by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ClipboardText }
    val ClipboardTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ClipboardTick }
    val Clock by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Clock }
    val CloseCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CloseCircle }
    val CloseSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CloseSquare }
    val Cloud by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Cloud }
    val CloudAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CloudAdd }
    val CloudChange by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CloudChange }
    val CloudConnection by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CloudConnection }
    val CloudCross by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CloudCross }
    val CloudDrizzle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CloudDrizzle }
    val CloudFog by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CloudFog }
    val CloudLightning by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CloudLightning }
    val CloudMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CloudMinus }
    val CloudNotif by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CloudNotif }
    val CloudPlus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CloudPlus }
    val CloudRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CloudRemove }
    val CloudSnow by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CloudSnow }
    val CloudSunny by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CloudSunny }
    val Code by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Code }
    val CodeCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CodeCircle }
    val CodeOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CodeOne }
    val Coffee by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Coffee }
    val Coin by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Coin }
    val CoinOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CoinOne }
    val ColorSwatch by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ColorSwatch }
    val Colorfilter by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Colorfilter }
    val ColorsSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ColorsSquare }
    val Command by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Command }
    val CommandSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CommandSquare }
    val Component by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Component }
    val Computing by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Computing }
    val Convert by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Convert }
    val ConvertCard by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ConvertCard }
    val ConvertThreedCube by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ConvertThreedCube }
    val Convertshape by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Convertshape }
    val ConvertshapeTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ConvertshapeTwo }
    val Copy by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Copy }
    val CopySuccess by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CopySuccess }
    val Copyright by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Copyright }
    val Courthouse by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Courthouse }
    val Cpu by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Cpu }
    val CpuCharge by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CpuCharge }
    val CpuSetting by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CpuSetting }
    val CreativeCommons by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CreativeCommons }
    val Crop by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Crop }
    val Crown by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Crown }
    val CrownOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.CrownOne }
    val Cup by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Cup }
    val Cut by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Cut }
    val Dai by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Dai }
    val Danger by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Danger }
    val Dash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Dash }
    val Data by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Data }
    val DataTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DataTwo }
    val Decred by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Decred }
    val Dent by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Dent }
    val Designtools by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Designtools }
    val DeviceMessage by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DeviceMessage }
    val Devices by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Devices }
    val Diagram by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Diagram }
    val Diamonds by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Diamonds }
    val Direct by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Direct }
    val DirectDown by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DirectDown }
    val DirectInbox by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DirectInbox }
    val DirectLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DirectLeft }
    val DirectNormal by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DirectNormal }
    val DirectNotification by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DirectNotification }
    val DirectRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DirectRight }
    val DirectSend by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DirectSend }
    val DirectUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DirectUp }
    val DirectboxDefault by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DirectboxDefault }
    val DirectboxNotif by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DirectboxNotif }
    val DirectboxReceive by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DirectboxReceive }
    val DirectboxSend by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DirectboxSend }
    val DiscountCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DiscountCircle }
    val DiscountShape by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DiscountShape }
    val Discover by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Discover }
    val Dislike by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Dislike }
    val Document by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Document }
    val DocumentCloud by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DocumentCloud }
    val DocumentCode by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DocumentCode }
    val DocumentCodeTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DocumentCodeTwo }
    val DocumentCopy by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DocumentCopy }
    val DocumentDownload by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DocumentDownload }
    val DocumentFavorite by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DocumentFavorite }
    val DocumentFilter by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DocumentFilter }
    val DocumentForward by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DocumentForward }
    val DocumentLike by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DocumentLike }
    val DocumentNormal by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DocumentNormal }
    val DocumentPrevious by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DocumentPrevious }
    val DocumentSketch by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DocumentSketch }
    val DocumentText by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DocumentText }
    val DocumentTextOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DocumentTextOne }
    val DocumentUpload by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DocumentUpload }
    val DollarCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DollarCircle }
    val DollarSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DollarSquare }
    val Dribbble by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Dribbble }
    val Driver by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Driver }
    val DriverRefresh by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DriverRefresh }
    val DriverTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.DriverTwo }
    val Driving by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Driving }
    val Drop by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Drop }
    val Dropbox by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Dropbox }
    val Edit by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Edit }
    val EditTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.EditTwo }
    val Educare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Educare }
    val Electricity by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Electricity }
    val Element by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Element }
    val ElementEqual by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ElementEqual }
    val ElementFour by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ElementFour }
    val ElementPlus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ElementPlus }
    val ElementThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ElementThree }
    val ElementTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ElementTwo }
    val Emercoin by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Emercoin }
    val EmojiHappy by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.EmojiHappy }
    val EmojiNormal by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.EmojiNormal }
    val EmojiSad by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.EmojiSad }
    val EmptyWallet by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.EmptyWallet }
    val EmptyWalletAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.EmptyWalletAdd }
    val EmptyWalletChange by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.EmptyWalletChange }
    val EmptyWalletRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.EmptyWalletRemove }
    val EmptyWalletTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.EmptyWalletTick }
    val EmptyWalletTime by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.EmptyWalletTime }
    val EnjinCoin by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.EnjinCoin }
    val Eos by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Eos }
    val Eraser by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Eraser }
    val EraserSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.EraserSquare }
    val Ethereum by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Ethereum }
    val EthereumClassic by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.EthereumClassic }
    val Export by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Export }
    val ExportCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ExportCircle }
    val ExportCurve by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ExportCurve }
    val ExportSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ExportSquare }
    val ExternalDrive by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ExternalDrive }
    val Eye by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Eye }
    val EyeSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.EyeSlash }
    val Facebook by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Facebook }
    val Fatrows by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Fatrows }
    val FavoriteChart by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FavoriteChart }
    val Figma by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Figma }
    val FigmaOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FigmaOne }
    val Filter by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Filter }
    val FilterAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FilterAdd }
    val FilterEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FilterEdit }
    val FilterRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FilterRemove }
    val FilterSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FilterSearch }
    val FilterSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FilterSquare }
    val FilterTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FilterTick }
    val FingerCricle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FingerCricle }
    val FingerScan by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FingerScan }
    val Firstline by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Firstline }
    val Flag by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Flag }
    val FlagTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FlagTwo }
    val Flash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Flash }
    val FlashCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FlashCircle }
    val FlashSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FlashSlash }
    val Flashy by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Flashy }
    val Folder by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Folder }
    val FolderAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FolderAdd }
    val FolderCloud by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FolderCloud }
    val FolderConnection by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FolderConnection }
    val FolderCross by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FolderCross }
    val FolderFavorite by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FolderFavorite }
    val FolderMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FolderMinus }
    val FolderOpen by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FolderOpen }
    val FolderTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FolderTwo }
    val Forbidden by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Forbidden }
    val ForbiddenTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ForbiddenTwo }
    val FormatCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FormatCircle }
    val FormatSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FormatSquare }
    val Forward by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Forward }
    val ForwardFifteenSeconds by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ForwardFifteenSeconds }
    val ForwardFiveSeconds by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ForwardFiveSeconds }
    val ForwardItem by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ForwardItem }
    val ForwardTenSeconds by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ForwardTenSeconds }
    val Framer by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Framer }
    val FtxToken by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.FtxToken }
    val Gallery by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Gallery }
    val GalleryAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GalleryAdd }
    val GalleryEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GalleryEdit }
    val GalleryExport by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GalleryExport }
    val GalleryFavorite by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GalleryFavorite }
    val GalleryImport by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GalleryImport }
    val GalleryRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GalleryRemove }
    val GallerySlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GallerySlash }
    val GalleryTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GalleryTick }
    val Game by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Game }
    val Gameboy by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Gameboy }
    val GasStation by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GasStation }
    val Gemini by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Gemini }
    val GeminiTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GeminiTwo }
    val Ghost by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Ghost }
    val Gift by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Gift }
    val Glass by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Glass }
    val Global by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Global }
    val GlobalEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GlobalEdit }
    val GlobalRefresh by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GlobalRefresh }
    val GlobalSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GlobalSearch }
    val Google by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Google }
    val GoogleDrive by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GoogleDrive }
    val GooglePlay by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GooglePlay }
    val Gps by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Gps }
    val GpsSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GpsSlash }
    val Grammerly by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Grammerly }
    val Graph by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Graph }
    val GridEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GridEdit }
    val GridEight by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GridEight }
    val GridEraser by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GridEraser }
    val GridFive by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GridFive }
    val GridFour by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GridFour }
    val GridLock by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GridLock }
    val GridNine by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GridNine }
    val GridOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GridOne }
    val GridSeven by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GridSeven }
    val GridSix by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GridSix }
    val GridThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GridThree }
    val GridTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.GridTwo }
    val HamburgerMenu by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HamburgerMenu }
    val Happyemoji by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Happyemoji }
    val Harmony by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Harmony }
    val Hashtag by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Hashtag }
    val HashtagDown by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HashtagDown }
    val HashtagSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HashtagSquare }
    val HashtagUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HashtagUp }
    val Headphone by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Headphone }
    val Headphones by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Headphones }
    val Health by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Health }
    val Heart by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Heart }
    val HeartAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HeartAdd }
    val HeartCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HeartCircle }
    val HeartEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HeartEdit }
    val HeartRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HeartRemove }
    val HeartSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HeartSearch }
    val HeartSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HeartSlash }
    val HeartTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HeartTick }
    val HederaHashgraph by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HederaHashgraph }
    val Hex by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Hex }
    val Hierarchy by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Hierarchy }
    val HierarchySquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HierarchySquare }
    val HierarchySquareThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HierarchySquareThree }
    val HierarchySquareTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HierarchySquareTwo }
    val HierarchyThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HierarchyThree }
    val HierarchyTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HierarchyTwo }
    val Home by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Home }
    val HomeHashtag by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HomeHashtag }
    val HomeThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HomeThree }
    val HomeTrendDown by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HomeTrendDown }
    val HomeTrendUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HomeTrendUp }
    val HomeTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HomeTwo }
    val HomeWifi by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HomeWifi }
    val Hospital by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Hospital }
    val House by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.House }
    val HouseTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HouseTwo }
    val HtmlFive by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HtmlFive }
    val HtmlThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HtmlThree }
    val HuobiToken by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.HuobiToken }
    val Icon by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Icon }
    val Illustrator by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Illustrator }
    val Image by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Image }
    val Import by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Import }
    val ImportCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ImportCircle }
    val ImportCurve by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ImportCurve }
    val ImportSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ImportSquare }
    val InfoCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.InfoCircle }
    val Information by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Information }
    val Instagram by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Instagram }
    val Iost by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Iost }
    val JavaScript by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.JavaScript }
    val Js by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Js }
    val Judge by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Judge }
    val Kanban by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Kanban }
    val Key by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Key }
    val KeySquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.KeySquare }
    val Keyboard by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Keyboard }
    val KeyboardOpen by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.KeyboardOpen }
    val KyberNetwork by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.KyberNetwork }
    val Lamp by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Lamp }
    val LampCharge by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LampCharge }
    val LampOn by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LampOn }
    val LampSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LampSlash }
    val LanguageCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LanguageCircle }
    val LanguageSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LanguageSquare }
    val Layer by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Layer }
    val LayoutMaximize by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LayoutMaximize }
    val Level by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Level }
    val Lifebuoy by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Lifebuoy }
    val Like by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Like }
    val LikeDislike by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LikeDislike }
    val LikeOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LikeOne }
    val LikeShapes by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LikeShapes }
    val LikeTag by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LikeTag }
    val Link by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Link }
    val LinkCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LinkCircle }
    val LinkOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LinkOne }
    val LinkSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LinkSquare }
    val LinkTwentyOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LinkTwentyOne }
    val LinkTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LinkTwo }
    val Litecoin by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Litecoin }
    val Location by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Location }
    val LocationAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LocationAdd }
    val LocationCross by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LocationCross }
    val LocationDiscover by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LocationDiscover }
    val LocationMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LocationMinus }
    val LocationSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LocationSlash }
    val LocationTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LocationTick }
    val Lock by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Lock }
    val LockCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LockCircle }
    val LockOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LockOne }
    val LockSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LockSlash }
    val Login by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Login }
    val LoginCurve by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LoginCurve }
    val Logout by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Logout }
    val LogoutCurve by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.LogoutCurve }
    val Lovely by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Lovely }
    val MagicStar by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MagicStar }
    val Magicpen by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Magicpen }
    val MainComponent by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MainComponent }
    val Maker by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Maker }
    val Man by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Man }
    val Map by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Map }
    val MapOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MapOne }
    val Mask by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Mask }
    val MaskLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MaskLeft }
    val MaskRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MaskRight }
    val Math by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Math }
    val Maximize by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Maximize }
    val MaximizeCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MaximizeCircle }
    val MaximizeFour by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MaximizeFour }
    val MaximizeOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MaximizeOne }
    val MaximizeThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MaximizeThree }
    val MaximizeTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MaximizeTwo }
    val Medal by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Medal }
    val MedalStar by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MedalStar }
    val Menu by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Menu }
    val MenuBoard by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MenuBoard }
    val Message by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Message }
    val MessageAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessageAdd }
    val MessageAddOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessageAddOne }
    val MessageCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessageCircle }
    val MessageEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessageEdit }
    val MessageFavorite by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessageFavorite }
    val MessageMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessageMinus }
    val MessageNotif by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessageNotif }
    val MessageProgramming by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessageProgramming }
    val MessageQuestion by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessageQuestion }
    val MessageRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessageRemove }
    val MessageSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessageSearch }
    val MessageSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessageSquare }
    val MessageText by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessageText }
    val MessageTextOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessageTextOne }
    val MessageTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessageTick }
    val MessageTime by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessageTime }
    val MessageTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessageTwo }
    val Messages by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Messages }
    val MessagesOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessagesOne }
    val MessagesThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessagesThree }
    val MessagesTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MessagesTwo }
    val Messenger by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Messenger }
    val Microphone by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Microphone }
    val MicrophoneSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MicrophoneSlash }
    val MicrophoneSlashOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MicrophoneSlashOne }
    val MicrophoneTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MicrophoneTwo }
    val Microscope by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Microscope }
    val Milk by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Milk }
    val MiniMusicSqaure by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MiniMusicSqaure }
    val Minus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Minus }
    val MinusCirlce by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MinusCirlce }
    val MinusSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MinusSquare }
    val Mirror by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Mirror }
    val MirroringScreen by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MirroringScreen }
    val Mobile by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Mobile }
    val MobileProgramming by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MobileProgramming }
    val Monero by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Monero }
    val Money by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Money }
    val MoneyAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MoneyAdd }
    val MoneyArchive by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MoneyArchive }
    val MoneyChange by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MoneyChange }
    val MoneyForbidden by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MoneyForbidden }
    val MoneyFour by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MoneyFour }
    val MoneyRecive by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MoneyRecive }
    val MoneyRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MoneyRemove }
    val MoneySend by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MoneySend }
    val MoneyThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MoneyThree }
    val MoneyTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MoneyTick }
    val MoneyTime by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MoneyTime }
    val MoneyTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MoneyTwo }
    val Moneys by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Moneys }
    val Monitor by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Monitor }
    val MonitorMobbile by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MonitorMobbile }
    val MonitorRecorder by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MonitorRecorder }
    val Moon by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Moon }
    val More by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.More }
    val MoreCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MoreCircle }
    val MoreSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MoreSquare }
    val MoreTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MoreTwo }
    val Mouse by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Mouse }
    val MouseCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MouseCircle }
    val MouseSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MouseSquare }
    val Music by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Music }
    val MusicCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MusicCircle }
    val MusicDashboard by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MusicDashboard }
    val MusicFilter by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MusicFilter }
    val MusicLibraryTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MusicLibraryTwo }
    val MusicPlay by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MusicPlay }
    val MusicPlaylist by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MusicPlaylist }
    val MusicSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MusicSquare }
    val MusicSquareAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MusicSquareAdd }
    val MusicSquareRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MusicSquareRemove }
    val MusicSquareSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.MusicSquareSearch }
    val Musicnote by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Musicnote }
    val Nebulas by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Nebulas }
    val Nem by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Nem }
    val Nexo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Nexo }
    val Next by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Next }
    val Note by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Note }
    val NoteAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.NoteAdd }
    val NoteFavorite by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.NoteFavorite }
    val NoteOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.NoteOne }
    val NoteRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.NoteRemove }
    val NoteSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.NoteSquare }
    val NoteText by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.NoteText }
    val Notepad by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Notepad }
    val NotepadTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.NotepadTwo }
    val Notification by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Notification }
    val NotificationBing by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.NotificationBing }
    val NotificationCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.NotificationCircle }
    val NotificationFavorite by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.NotificationFavorite }
    val NotificationOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.NotificationOne }
    val NotificationStatus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.NotificationStatus }
    val OceanProtocol by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.OceanProtocol }
    val Okb by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Okb }
    val Okru by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Okru }
    val OmegaCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.OmegaCircle }
    val OmegaSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.OmegaSquare }
    val Ontology by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Ontology }
    val Paintbucket by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Paintbucket }
    val Paperclip by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Paperclip }
    val PaperclipTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PaperclipTwo }
    val PasswordCheck by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PasswordCheck }
    val PathTool by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PathTool }
    val PathToolSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PathToolSquare }
    val PathToolTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PathToolTwo }
    val Pause by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Pause }
    val PauseCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PauseCircle }
    val Paypal by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Paypal }
    val PenAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PenAdd }
    val PenClose by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PenClose }
    val PenRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PenRemove }
    val PenTool by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PenTool }
    val PenToolTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PenToolTwo }
    val People by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.People }
    val PercentageCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PercentageCircle }
    val PercentageSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PercentageSquare }
    val Personalcard by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Personalcard }
    val Pet by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Pet }
    val Pharagraphspacing by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Pharagraphspacing }
    val Photoshop by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Photoshop }
    val PictureFrame by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PictureFrame }
    val Play by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Play }
    val PlayAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PlayAdd }
    val PlayCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PlayCircle }
    val PlayCricle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PlayCricle }
    val PlayRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PlayRemove }
    val Pointer by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Pointer }
    val Polkadot by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Polkadot }
    val Polygon by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Polygon }
    val Polyswarm by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Polyswarm }
    val PresentionChart by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PresentionChart }
    val Previous by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Previous }
    val Printer by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Printer }
    val PrinterSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.PrinterSlash }
    val Profile by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Profile }
    val ProfileAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ProfileAdd }
    val ProfileCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ProfileCircle }
    val ProfileDelete by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ProfileDelete }
    val ProfileRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ProfileRemove }
    val ProfileTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ProfileTick }
    val ProfileTwouser by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ProfileTwouser }
    val ProgrammingArrow by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ProgrammingArrow }
    val ProgrammingArrows by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ProgrammingArrows }
    val Python by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Python }
    val Quant by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Quant }
    val QuoteDown by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.QuoteDown }
    val QuoteDownCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.QuoteDownCircle }
    val QuoteDownSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.QuoteDownSquare }
    val QuoteUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.QuoteUp }
    val QuoteUpCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.QuoteUpCircle }
    val QuoteUpSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.QuoteUpSquare }
    val Radar by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Radar }
    val RadarTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RadarTwo }
    val Radio by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Radio }
    val Ram by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Ram }
    val RamTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RamTwo }
    val Rank by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Rank }
    val Ranking by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Ranking }
    val Receipt by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Receipt }
    val ReceiptAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ReceiptAdd }
    val ReceiptDiscount by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ReceiptDiscount }
    val ReceiptDisscount by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ReceiptDisscount }
    val ReceiptEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ReceiptEdit }
    val ReceiptItem by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ReceiptItem }
    val ReceiptMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ReceiptMinus }
    val ReceiptOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ReceiptOne }
    val ReceiptSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ReceiptSearch }
    val ReceiptSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ReceiptSquare }
    val ReceiptText by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ReceiptText }
    val ReceiptTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ReceiptTwo }
    val ReceiptTwoOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ReceiptTwoOne }
    val Receive by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Receive }
    val ReceiveSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ReceiveSquare }
    val ReceiveSquareTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ReceiveSquareTwo }
    val Record by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Record }
    val RecordCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RecordCircle }
    val RecoveryConvert by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RecoveryConvert }
    val Refresh by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Refresh }
    val RefreshCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RefreshCircle }
    val RefreshLeftSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RefreshLeftSquare }
    val RefreshRightSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RefreshRightSquare }
    val RefreshSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RefreshSquare }
    val RefreshTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RefreshTwo }
    val Repeat by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Repeat }
    val RepeatCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RepeatCircle }
    val RepeateMusic by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RepeateMusic }
    val RepeateOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RepeateOne }
    val Reserve by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Reserve }
    val RotateLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RotateLeft }
    val RotateRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RotateRight }
    val RouteSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RouteSquare }
    val Routing by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Routing }
    val RoutingTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RoutingTwo }
    val RowHorizontal by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RowHorizontal }
    val RowVertical by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RowVertical }
    val Ruler by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Ruler }
    val RulerPen by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.RulerPen }
    val SafeHome by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SafeHome }
    val Sagittarius by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Sagittarius }
    val SaveAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SaveAdd }
    val SaveMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SaveMinus }
    val SaveRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SaveRemove }
    val SaveTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SaveTwo }
    val Scan by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Scan }
    val ScanBarcode by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ScanBarcode }
    val Scanner by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Scanner }
    val Scanning by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Scanning }
    val Scissor by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Scissor }
    val Screenmirroring by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Screenmirroring }
    val Scroll by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Scroll }
    val SearchFavorite by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SearchFavorite }
    val SearchFavoriteOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SearchFavoriteOne }
    val SearchNormal by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SearchNormal }
    val SearchNormalOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SearchNormalOne }
    val SearchStatus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SearchStatus }
    val SearchStatusOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SearchStatusOne }
    val SearchZoomIn by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SearchZoomIn }
    val SearchZoomInOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SearchZoomInOne }
    val SearchZoomOut by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SearchZoomOut }
    val SearchZoomOutOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SearchZoomOutOne }
    val Security by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Security }
    val SecurityCard by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SecurityCard }
    val SecuritySafe by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SecuritySafe }
    val SecurityTime by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SecurityTime }
    val SecurityUser by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SecurityUser }
    val Send by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Send }
    val SendTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SendTwo }
    val Setting by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Setting }
    val SettingFive by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SettingFive }
    val SettingFour by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SettingFour }
    val SettingThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SettingThree }
    val SettingTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SettingTwo }
    val Settings by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Settings }
    val Shapes by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Shapes }
    val ShapesOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ShapesOne }
    val Share by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Share }
    val Shield by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Shield }
    val ShieldCross by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ShieldCross }
    val ShieldSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ShieldSearch }
    val ShieldSecurity by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ShieldSecurity }
    val ShieldSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ShieldSlash }
    val ShieldTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ShieldTick }
    val Ship by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Ship }
    val Shop by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Shop }
    val ShopAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ShopAdd }
    val ShopRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ShopRemove }
    val ShoppingBag by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ShoppingBag }
    val ShoppingCart by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ShoppingCart }
    val Shuffle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Shuffle }
    val Shutterstock by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Shutterstock }
    val Siacoin by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Siacoin }
    val SidebarBottom by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SidebarBottom }
    val SidebarLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SidebarLeft }
    val SidebarRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SidebarRight }
    val SidebarTop by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SidebarTop }
    val Signpost by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Signpost }
    val Simcard by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Simcard }
    val SimcardOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SimcardOne }
    val SimcardTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SimcardTwo }
    val Size by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Size }
    val Slack by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Slack }
    val Slash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Slash }
    val Slider by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Slider }
    val SliderHorizontal by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SliderHorizontal }
    val SliderHorizontalOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SliderHorizontalOne }
    val SliderVertical by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SliderVertical }
    val SliderVerticalOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SliderVerticalOne }
    val Smallcaps by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Smallcaps }
    val SmartCar by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SmartCar }
    val SmartHome by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SmartHome }
    val Smileys by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Smileys }
    val Sms by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Sms }
    val SmsEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SmsEdit }
    val SmsNotification by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SmsNotification }
    val SmsSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SmsSearch }
    val SmsStar by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SmsStar }
    val SmsTracking by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SmsTracking }
    val Snapchat by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Snapchat }
    val Solana by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Solana }
    val Sort by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Sort }
    val Sound by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Sound }
    val Speaker by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Speaker }
    val Speedometer by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Speedometer }
    val Spotify by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Spotify }
    val Stacks by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Stacks }
    val Star by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Star }
    val StarOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.StarOne }
    val StarSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.StarSlash }
    val Status by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Status }
    val StatusUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.StatusUp }
    val Stellar by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Stellar }
    val Sticker by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Sticker }
    val Stickynote by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Stickynote }
    val Stop by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Stop }
    val StopCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.StopCircle }
    val Story by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Story }
    val Strongbox by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Strongbox }
    val StrongboxTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.StrongboxTwo }
    val Subtitle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Subtitle }
    val Sun by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Sun }
    val SunFog by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SunFog }
    val SunOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.SunOne }
    val TableDocument by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TableDocument }
    val TableLamp by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TableLamp }
    val Tag by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Tag }
    val TagCross by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TagCross }
    val TagRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TagRight }
    val TagTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TagTwo }
    val TagUser by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TagUser }
    val Task by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Task }
    val TaskSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TaskSquare }
    val Teacher by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Teacher }
    val Tenx by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Tenx }
    val Tether by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Tether }
    val Text by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Text }
    val TextBlock by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TextBlock }
    val TextBold by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TextBold }
    val TextItalic by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TextItalic }
    val TextUnderline by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TextUnderline }
    val TextalignCenter by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TextalignCenter }
    val TextalignJustifycenter by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TextalignJustifycenter }
    val TextalignJustifyleft by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TextalignJustifyleft }
    val TextalignJustifyright by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TextalignJustifyright }
    val TextalignLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TextalignLeft }
    val TextalignRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TextalignRight }
    val TheGraph by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TheGraph }
    val Theta by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Theta }
    val Thorchain by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Thorchain }
    val ThreedCubeScan by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ThreedCubeScan }
    val ThreedRotate by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ThreedRotate }
    val ThreedSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ThreedSquare }
    val Threedcube by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Threedcube }
    val Threesquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Threesquare }
    val TickCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TickCircle }
    val TickSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TickSquare }
    val Ticket by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Ticket }
    val TicketDiscount by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TicketDiscount }
    val TicketExpired by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TicketExpired }
    val TicketStar by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TicketStar }
    val TicketTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TicketTwo }
    val Timer by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Timer }
    val TimerOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TimerOne }
    val TimerPause by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TimerPause }
    val TimerStart by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TimerStart }
    val ToggleOff by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ToggleOff }
    val ToggleOffCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ToggleOffCircle }
    val ToggleOn by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ToggleOn }
    val ToggleOnCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.ToggleOnCircle }
    val Trade by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Trade }
    val TransactionMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TransactionMinus }
    val Translate by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Translate }
    val Transmit by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Transmit }
    val TransmitSqaureTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TransmitSqaureTwo }
    val TransmitSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TransmitSquare }
    val Trash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Trash }
    val Tree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Tree }
    val Trello by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Trello }
    val TrendDown by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TrendDown }
    val TrendUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TrendUp }
    val Triangle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Triangle }
    val TriangleLogo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TriangleLogo }
    val Trontron by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Trontron }
    val Truck by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Truck }
    val TruckFast by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TruckFast }
    val TruckRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TruckRemove }
    val TruckTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TruckTick }
    val TruckTime by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TruckTime }
    val TrushSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TrushSquare }
    val TwentyFourSupport by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.TwentyFourSupport }
    val Twitch by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Twitch }
    val Uieight by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Uieight }
    val Unlimited by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Unlimited }
    val Unlock by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Unlock }
    val UsdCoin by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.UsdCoin }
    val User by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.User }
    val UserAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.UserAdd }
    val UserCirlceAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.UserCirlceAdd }
    val UserEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.UserEdit }
    val UserMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.UserMinus }
    val UserOctagon by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.UserOctagon }
    val UserRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.UserRemove }
    val UserSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.UserSearch }
    val UserSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.UserSquare }
    val UserTag by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.UserTag }
    val UserTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.UserTick }
    val Velas by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Velas }
    val Verify by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Verify }
    val Vibe by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Vibe }
    val Video by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Video }
    val VideoAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VideoAdd }
    val VideoCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VideoCircle }
    val VideoHorizontal by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VideoHorizontal }
    val VideoOctagon by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VideoOctagon }
    val VideoPlay by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VideoPlay }
    val VideoRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VideoRemove }
    val VideoSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VideoSlash }
    val VideoSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VideoSquare }
    val VideoTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VideoTick }
    val VideoTime by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VideoTime }
    val VideoVertical by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VideoVertical }
    val VoiceCricle by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VoiceCricle }
    val VoiceSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VoiceSquare }
    val Volume by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Volume }
    val VolumeCross by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VolumeCross }
    val VolumeHigh by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VolumeHigh }
    val VolumeLow by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VolumeLow }
    val VolumeLowOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VolumeLowOne }
    val VolumeMute by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VolumeMute }
    val VolumeSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VolumeSlash }
    val VolumeUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.VolumeUp }
    val Wallet by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Wallet }
    val WalletAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.WalletAdd }
    val WalletAddOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.WalletAddOne }
    val WalletCheck by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.WalletCheck }
    val WalletMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.WalletMinus }
    val WalletMoney by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.WalletMoney }
    val WalletOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.WalletOne }
    val WalletRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.WalletRemove }
    val WalletSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.WalletSearch }
    val WalletThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.WalletThree }
    val WalletTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.WalletTwo }
    val Wanchain by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Wanchain }
    val WanchainOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.WanchainOne }
    val WarningTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.WarningTwo }
    val Watch by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Watch }
    val WatchStatus by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.WatchStatus }
    val Weight by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Weight }
    val WeightMeter by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.WeightMeter }
    val Whatsapp by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Whatsapp }
    val Wifi by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Wifi }
    val WifiSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.WifiSquare }
    val Wind by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Wind }
    val WindTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.WindTwo }
    val Windows by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Windows }
    val Wing by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Wing }
    val Woman by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Woman }
    val WristClock by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.WristClock }
    val Xd by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Xd }
    val Xiaomi by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Xiaomi }
    val Xrp by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Xrp }
    val Youtube by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Youtube }
    val Zel by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Zel }
    val Zoom by lazy { com.github.yohannestz.iconsax_compose.iconsax.outline.Zoom }
}
