package com.github.yohannestz.iconsax_compose.iconsax
object IconsaxBroken {
    val Aave by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Aave }
    val Activity by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Activity }
    val Add by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Add }
    val AddCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.AddCircle }
    val AddSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.AddSquare }
    val Additem by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Additem }
    val Airdrop by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Airdrop }
    val Airplane by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Airplane }
    val AirplaneSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.AirplaneSquare }
    val Airpod by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Airpod }
    val Airpods by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Airpods }
    val Alarm by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Alarm }
    val AlignBottom by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.AlignBottom }
    val AlignHorizontally by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.AlignHorizontally }
    val AlignLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.AlignLeft }
    val AlignRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.AlignRight }
    val AlignTop by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.AlignTop }
    val AlignVertically by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.AlignVertically }
    val Android by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Android }
    val Ankr by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Ankr }
    val Apple by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Apple }
    val Aquarius by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Aquarius }
    val Archive by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Archive }
    val ArchiveAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArchiveAdd }
    val ArchiveBook by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArchiveBook }
    val ArchiveBox by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArchiveBox }
    val ArchiveMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArchiveMinus }
    val ArchiveSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArchiveSlash }
    val ArchiveTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArchiveTick }
    val ArrangeHorizontal by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrangeHorizontal }
    val ArrangeHorizontalCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrangeHorizontalCircle }
    val ArrangeHorizontalSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrangeHorizontalSquare }
    val ArrangeVertical by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrangeVertical }
    val ArrangeVerticalCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrangeVerticalCircle }
    val ArrangeVerticalSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrangeVerticalSquare }
    val Arrow by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Arrow }
    val ArrowCircleDown by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowCircleDown }
    val ArrowCircleDownTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowCircleDownTwo }
    val ArrowCircleLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowCircleLeft }
    val ArrowCircleLeftTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowCircleLeftTwo }
    val ArrowCircleRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowCircleRight }
    val ArrowCircleRightTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowCircleRightTwo }
    val ArrowCircleUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowCircleUp }
    val ArrowCircleUpTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowCircleUpTwo }
    val ArrowDown by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowDown }
    val ArrowDownThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowDownThree }
    val ArrowDownTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowDownTwo }
    val ArrowForward by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowForward }
    val ArrowForwardSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowForwardSquare }
    val ArrowLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowLeft }
    val ArrowLeftThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowLeftThree }
    val ArrowLeftTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowLeftTwo }
    val ArrowRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowRight }
    val ArrowRightThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowRightThree }
    val ArrowRightTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowRightTwo }
    val ArrowRotateLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowRotateLeft }
    val ArrowRotateRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowRotateRight }
    val ArrowSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowSquare }
    val ArrowSquareDown by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowSquareDown }
    val ArrowSquareLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowSquareLeft }
    val ArrowSquareRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowSquareRight }
    val ArrowSquareUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowSquareUp }
    val ArrowSwapHorizontal by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowSwapHorizontal }
    val ArrowSwapVertical by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowSwapVertical }
    val ArrowUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowUp }
    val ArrowUpThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowUpThree }
    val ArrowUpTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ArrowUpTwo }
    val AttachCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.AttachCircle }
    val AttachSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.AttachSquare }
    val AudioSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.AudioSquare }
    val Augur by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Augur }
    val Autobrightness by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Autobrightness }
    val Autonio by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Autonio }
    val Avalanche by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Avalanche }
    val Award by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Award }
    val Back by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Back }
    val BackSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BackSquare }
    val Backward by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Backward }
    val BackwardFifteenSeconds by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BackwardFifteenSeconds }
    val BackwardFiveSeconds by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BackwardFiveSeconds }
    val BackwardItem by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BackwardItem }
    val BackwardTenSeconds by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BackwardTenSeconds }
    val Bag by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Bag }
    val BagCross by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BagCross }
    val BagCrossOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BagCrossOne }
    val BagHappy by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BagHappy }
    val BagTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BagTick }
    val BagTickTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BagTickTwo }
    val BagTimer by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BagTimer }
    val BagTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BagTwo }
    val Bank by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Bank }
    val Barcode by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Barcode }
    val BatteryCharging by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BatteryCharging }
    val BatteryDisable by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BatteryDisable }
    val BatteryEmpty by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BatteryEmpty }
    val BatteryEmptyOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BatteryEmptyOne }
    val BatteryFull by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BatteryFull }
    val Be by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Be }
    val Bezier by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Bezier }
    val Bill by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Bill }
    val BinanceCoin by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BinanceCoin }
    val BinanceUsd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BinanceUsd }
    val Bitcoin by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Bitcoin }
    val BitcoinCard by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BitcoinCard }
    val BitcoinConvert by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BitcoinConvert }
    val BitcoinRefresh by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BitcoinRefresh }
    val Blend by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Blend }
    val BlendTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BlendTwo }
    val Blogger by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Blogger }
    val Bluetooth by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Bluetooth }
    val BluetoothCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BluetoothCircle }
    val BluetoothRectangle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BluetoothRectangle }
    val BluetoothTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BluetoothTwo }
    val Blur by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Blur }
    val Book by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Book }
    val BookOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BookOne }
    val BookSaved by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BookSaved }
    val BookSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BookSquare }
    val Bookmark by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Bookmark }
    val BookmarkTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BookmarkTwo }
    val Bootstrap by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Bootstrap }
    val Box by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Box }
    val BoxAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BoxAdd }
    val BoxOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BoxOne }
    val BoxRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BoxRemove }
    val BoxSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BoxSearch }
    val BoxTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BoxTick }
    val BoxTime by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BoxTime }
    val BoxTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BoxTwo }
    val Briefcase by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Briefcase }
    val BrifecaseCross by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BrifecaseCross }
    val BrifecaseTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BrifecaseTick }
    val BrifecaseTimer by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BrifecaseTimer }
    val Brodcast by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Brodcast }
    val Broom by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Broom }
    val Brush by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Brush }
    val BrushBig by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BrushBig }
    val BrushSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BrushSquare }
    val BrushThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BrushThree }
    val BrushTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BrushTwo }
    val Bubble by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Bubble }
    val Bucket by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Bucket }
    val BucketCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BucketCircle }
    val BucketSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BucketSquare }
    val Building by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Building }
    val BuildingFour by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BuildingFour }
    val BuildingThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BuildingThree }
    val Buildings by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Buildings }
    val BuildingsTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BuildingsTwo }
    val Buliding by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Buliding }
    val Bus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Bus }
    val BuyCrypto by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.BuyCrypto }
    val Cake by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Cake }
    val Calculator by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Calculator }
    val Calendar by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Calendar }
    val CalendarAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CalendarAdd }
    val CalendarCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CalendarCircle }
    val CalendarEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CalendarEdit }
    val CalendarOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CalendarOne }
    val CalendarRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CalendarRemove }
    val CalendarSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CalendarSearch }
    val CalendarTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CalendarTick }
    val CalendarTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CalendarTwo }
    val Call by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Call }
    val CallAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CallAdd }
    val CallCalling by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CallCalling }
    val CallIncoming by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CallIncoming }
    val CallMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CallMinus }
    val CallOutgoing by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CallOutgoing }
    val CallReceived by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CallReceived }
    val CallRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CallRemove }
    val CallSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CallSlash }
    val Camera by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Camera }
    val CameraSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CameraSlash }
    val Candle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Candle }
    val CandleTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CandleTwo }
    val Car by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Car }
    val Card by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Card }
    val CardAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CardAdd }
    val CardCoin by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CardCoin }
    val CardEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CardEdit }
    val CardPos by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CardPos }
    val CardReceive by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CardReceive }
    val CardRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CardRemove }
    val CardRemoveOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CardRemoveOne }
    val CardSend by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CardSend }
    val CardSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CardSlash }
    val CardTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CardTick }
    val CardTickOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CardTickOne }
    val Cardano by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Cardano }
    val Cards by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Cards }
    val Category by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Category }
    val CategoryTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CategoryTwo }
    val Cd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Cd }
    val Celo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Celo }
    val Celsius by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Celsius }
    val Chainlink by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Chainlink }
    val Chart by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Chart }
    val ChartCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ChartCircle }
    val ChartFail by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ChartFail }
    val ChartOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ChartOne }
    val ChartSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ChartSquare }
    val ChartSuccess by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ChartSuccess }
    val ChartTwentyOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ChartTwentyOne }
    val ChartTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ChartTwo }
    val Check by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Check }
    val ChemicalGlass by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ChemicalGlass }
    val Chrome by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Chrome }
    val Civic by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Civic }
    val Clipboard by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Clipboard }
    val ClipboardClose by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ClipboardClose }
    val ClipboardExport by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ClipboardExport }
    val ClipboardImport by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ClipboardImport }
    val ClipboardText by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ClipboardText }
    val ClipboardTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ClipboardTick }
    val Clock by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Clock }
    val CloseCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CloseCircle }
    val CloseSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CloseSquare }
    val Cloud by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Cloud }
    val CloudAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CloudAdd }
    val CloudChange by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CloudChange }
    val CloudConnection by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CloudConnection }
    val CloudCross by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CloudCross }
    val CloudDrizzle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CloudDrizzle }
    val CloudFog by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CloudFog }
    val CloudLightning by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CloudLightning }
    val CloudMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CloudMinus }
    val CloudNotif by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CloudNotif }
    val CloudPlus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CloudPlus }
    val CloudRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CloudRemove }
    val CloudSnow by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CloudSnow }
    val CloudSunny by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CloudSunny }
    val Code by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Code }
    val CodeCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CodeCircle }
    val CodeOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CodeOne }
    val Coffee by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Coffee }
    val Coin by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Coin }
    val CoinOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CoinOne }
    val ColorSwatch by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ColorSwatch }
    val Colorfilter by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Colorfilter }
    val ColorsSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ColorsSquare }
    val Command by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Command }
    val CommandSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CommandSquare }
    val Component by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Component }
    val Computing by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Computing }
    val Convert by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Convert }
    val ConvertCard by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ConvertCard }
    val ConvertThreedCube by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ConvertThreedCube }
    val Convertshape by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Convertshape }
    val ConvertshapeTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ConvertshapeTwo }
    val Copy by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Copy }
    val CopySuccess by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CopySuccess }
    val Copyright by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Copyright }
    val Courthouse by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Courthouse }
    val Cpu by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Cpu }
    val CpuCharge by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CpuCharge }
    val CpuSetting by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CpuSetting }
    val CreativeCommons by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CreativeCommons }
    val Crop by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Crop }
    val Crown by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Crown }
    val CrownOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.CrownOne }
    val Cup by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Cup }
    val Cut by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Cut }
    val Dai by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Dai }
    val Danger by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Danger }
    val Dash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Dash }
    val Data by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Data }
    val DataTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DataTwo }
    val Decred by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Decred }
    val Dent by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Dent }
    val Designtools by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Designtools }
    val DeviceMessage by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DeviceMessage }
    val Devices by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Devices }
    val Diagram by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Diagram }
    val Diamonds by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Diamonds }
    val Direct by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Direct }
    val DirectDown by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DirectDown }
    val DirectInbox by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DirectInbox }
    val DirectLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DirectLeft }
    val DirectNormal by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DirectNormal }
    val DirectNotification by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DirectNotification }
    val DirectRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DirectRight }
    val DirectSend by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DirectSend }
    val DirectUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DirectUp }
    val DirectboxDefault by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DirectboxDefault }
    val DirectboxNotif by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DirectboxNotif }
    val DirectboxReceive by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DirectboxReceive }
    val DirectboxSend by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DirectboxSend }
    val DiscountCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DiscountCircle }
    val DiscountShape by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DiscountShape }
    val Discover by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Discover }
    val Dislike by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Dislike }
    val Document by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Document }
    val DocumentCloud by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DocumentCloud }
    val DocumentCode by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DocumentCode }
    val DocumentCodeTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DocumentCodeTwo }
    val DocumentCopy by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DocumentCopy }
    val DocumentDownload by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DocumentDownload }
    val DocumentFavorite by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DocumentFavorite }
    val DocumentFilter by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DocumentFilter }
    val DocumentForward by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DocumentForward }
    val DocumentLike by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DocumentLike }
    val DocumentNormal by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DocumentNormal }
    val DocumentPrevious by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DocumentPrevious }
    val DocumentSketch by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DocumentSketch }
    val DocumentText by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DocumentText }
    val DocumentTextOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DocumentTextOne }
    val DocumentUpload by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DocumentUpload }
    val DollarCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DollarCircle }
    val DollarSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DollarSquare }
    val Dribbble by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Dribbble }
    val Driver by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Driver }
    val DriverRefresh by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DriverRefresh }
    val DriverTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.DriverTwo }
    val Driving by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Driving }
    val Drop by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Drop }
    val Dropbox by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Dropbox }
    val Edit by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Edit }
    val EditTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.EditTwo }
    val Educare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Educare }
    val Electricity by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Electricity }
    val Element by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Element }
    val ElementEqual by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ElementEqual }
    val ElementFour by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ElementFour }
    val ElementPlus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ElementPlus }
    val ElementThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ElementThree }
    val ElementTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ElementTwo }
    val Emercoin by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Emercoin }
    val EmojiHappy by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.EmojiHappy }
    val EmojiNormal by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.EmojiNormal }
    val EmojiSad by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.EmojiSad }
    val EmptyWallet by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.EmptyWallet }
    val EmptyWalletAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.EmptyWalletAdd }
    val EmptyWalletChange by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.EmptyWalletChange }
    val EmptyWalletRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.EmptyWalletRemove }
    val EmptyWalletTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.EmptyWalletTick }
    val EmptyWalletTime by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.EmptyWalletTime }
    val EnjinCoin by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.EnjinCoin }
    val Eos by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Eos }
    val Eraser by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Eraser }
    val EraserSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.EraserSquare }
    val Ethereum by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Ethereum }
    val EthereumClassic by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.EthereumClassic }
    val Export by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Export }
    val ExportCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ExportCircle }
    val ExportCurve by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ExportCurve }
    val ExportSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ExportSquare }
    val ExternalDrive by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ExternalDrive }
    val Eye by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Eye }
    val EyeSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.EyeSlash }
    val Facebook by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Facebook }
    val Fatrows by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Fatrows }
    val FavoriteChart by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FavoriteChart }
    val Figma by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Figma }
    val FigmaOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FigmaOne }
    val Filter by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Filter }
    val FilterAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FilterAdd }
    val FilterEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FilterEdit }
    val FilterRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FilterRemove }
    val FilterSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FilterSearch }
    val FilterSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FilterSquare }
    val FilterTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FilterTick }
    val FingerCricle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FingerCricle }
    val FingerScan by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FingerScan }
    val Firstline by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Firstline }
    val Flag by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Flag }
    val FlagTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FlagTwo }
    val Flash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Flash }
    val FlashCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FlashCircle }
    val FlashSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FlashSlash }
    val Flashy by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Flashy }
    val Folder by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Folder }
    val FolderAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FolderAdd }
    val FolderCloud by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FolderCloud }
    val FolderConnection by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FolderConnection }
    val FolderCross by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FolderCross }
    val FolderFavorite by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FolderFavorite }
    val FolderMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FolderMinus }
    val FolderOpen by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FolderOpen }
    val FolderTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FolderTwo }
    val Forbidden by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Forbidden }
    val ForbiddenTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ForbiddenTwo }
    val FormatCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FormatCircle }
    val FormatSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FormatSquare }
    val Forward by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Forward }
    val ForwardFifteenSeconds by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ForwardFifteenSeconds }
    val ForwardFiveSeconds by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ForwardFiveSeconds }
    val ForwardItem by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ForwardItem }
    val ForwardTenSeconds by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ForwardTenSeconds }
    val Framer by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Framer }
    val FtxToken by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.FtxToken }
    val Gallery by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Gallery }
    val GalleryAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GalleryAdd }
    val GalleryEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GalleryEdit }
    val GalleryExport by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GalleryExport }
    val GalleryFavorite by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GalleryFavorite }
    val GalleryImport by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GalleryImport }
    val GalleryRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GalleryRemove }
    val GallerySlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GallerySlash }
    val GalleryTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GalleryTick }
    val Game by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Game }
    val Gameboy by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Gameboy }
    val GasStation by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GasStation }
    val Gemini by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Gemini }
    val GeminiTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GeminiTwo }
    val Ghost by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Ghost }
    val Gift by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Gift }
    val Glass by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Glass }
    val Global by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Global }
    val GlobalEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GlobalEdit }
    val GlobalRefresh by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GlobalRefresh }
    val GlobalSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GlobalSearch }
    val Google by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Google }
    val GoogleDrive by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GoogleDrive }
    val GooglePlay by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GooglePlay }
    val Gps by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Gps }
    val GpsSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GpsSlash }
    val Grammerly by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Grammerly }
    val Graph by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Graph }
    val GridEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GridEdit }
    val GridEight by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GridEight }
    val GridEraser by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GridEraser }
    val GridFive by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GridFive }
    val GridFour by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GridFour }
    val GridLock by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GridLock }
    val GridNine by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GridNine }
    val GridOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GridOne }
    val GridSeven by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GridSeven }
    val GridSix by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GridSix }
    val GridThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GridThree }
    val GridTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.GridTwo }
    val HamburgerMenu by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HamburgerMenu }
    val Happyemoji by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Happyemoji }
    val Harmony by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Harmony }
    val Hashtag by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Hashtag }
    val HashtagDown by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HashtagDown }
    val HashtagSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HashtagSquare }
    val HashtagUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HashtagUp }
    val Headphone by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Headphone }
    val Headphones by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Headphones }
    val Health by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Health }
    val Heart by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Heart }
    val HeartAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HeartAdd }
    val HeartCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HeartCircle }
    val HeartEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HeartEdit }
    val HeartRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HeartRemove }
    val HeartSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HeartSearch }
    val HeartSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HeartSlash }
    val HeartTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HeartTick }
    val HederaHashgraph by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HederaHashgraph }
    val Hex by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Hex }
    val Hierarchy by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Hierarchy }
    val HierarchySquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HierarchySquare }
    val HierarchySquareThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HierarchySquareThree }
    val HierarchySquareTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HierarchySquareTwo }
    val HierarchyThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HierarchyThree }
    val HierarchyTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HierarchyTwo }
    val Home by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Home }
    val HomeHashtag by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HomeHashtag }
    val HomeThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HomeThree }
    val HomeTrendDown by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HomeTrendDown }
    val HomeTrendUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HomeTrendUp }
    val HomeTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HomeTwo }
    val HomeWifi by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HomeWifi }
    val Hospital by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Hospital }
    val House by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.House }
    val HouseTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HouseTwo }
    val HtmlFive by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HtmlFive }
    val HtmlThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HtmlThree }
    val HuobiToken by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.HuobiToken }
    val Icon by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Icon }
    val Illustrator by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Illustrator }
    val Image by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Image }
    val Import by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Import }
    val ImportCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ImportCircle }
    val ImportCurve by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ImportCurve }
    val ImportSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ImportSquare }
    val InfoCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.InfoCircle }
    val Information by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Information }
    val Instagram by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Instagram }
    val Iost by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Iost }
    val JavaScript by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.JavaScript }
    val Js by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Js }
    val Judge by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Judge }
    val Kanban by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Kanban }
    val Key by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Key }
    val KeySquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.KeySquare }
    val Keyboard by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Keyboard }
    val KeyboardOpen by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.KeyboardOpen }
    val KyberNetwork by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.KyberNetwork }
    val Lamp by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Lamp }
    val LampCharge by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LampCharge }
    val LampOn by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LampOn }
    val LampSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LampSlash }
    val LanguageCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LanguageCircle }
    val LanguageSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LanguageSquare }
    val Layer by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Layer }
    val LayoutMaximize by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LayoutMaximize }
    val Level by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Level }
    val Lifebuoy by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Lifebuoy }
    val Like by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Like }
    val LikeDislike by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LikeDislike }
    val LikeOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LikeOne }
    val LikeShapes by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LikeShapes }
    val LikeTag by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LikeTag }
    val Link by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Link }
    val LinkCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LinkCircle }
    val LinkOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LinkOne }
    val LinkSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LinkSquare }
    val LinkTwentyOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LinkTwentyOne }
    val LinkTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LinkTwo }
    val Litecoin by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Litecoin }
    val Location by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Location }
    val LocationAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LocationAdd }
    val LocationCross by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LocationCross }
    val LocationDiscover by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LocationDiscover }
    val LocationMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LocationMinus }
    val LocationSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LocationSlash }
    val LocationTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LocationTick }
    val Lock by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Lock }
    val LockCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LockCircle }
    val LockOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LockOne }
    val LockSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LockSlash }
    val Login by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Login }
    val LoginCurve by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LoginCurve }
    val Logout by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Logout }
    val LogoutCurve by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.LogoutCurve }
    val Lovely by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Lovely }
    val MagicStar by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MagicStar }
    val Magicpen by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Magicpen }
    val MainComponent by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MainComponent }
    val Maker by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Maker }
    val Man by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Man }
    val Map by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Map }
    val MapOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MapOne }
    val Mask by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Mask }
    val MaskLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MaskLeft }
    val MaskRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MaskRight }
    val Math by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Math }
    val Maximize by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Maximize }
    val MaximizeCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MaximizeCircle }
    val MaximizeFour by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MaximizeFour }
    val MaximizeOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MaximizeOne }
    val MaximizeThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MaximizeThree }
    val MaximizeTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MaximizeTwo }
    val Medal by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Medal }
    val MedalStar by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MedalStar }
    val Menu by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Menu }
    val MenuBoard by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MenuBoard }
    val Message by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Message }
    val MessageAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessageAdd }
    val MessageAddOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessageAddOne }
    val MessageCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessageCircle }
    val MessageEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessageEdit }
    val MessageFavorite by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessageFavorite }
    val MessageMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessageMinus }
    val MessageNotif by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessageNotif }
    val MessageProgramming by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessageProgramming }
    val MessageQuestion by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessageQuestion }
    val MessageRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessageRemove }
    val MessageSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessageSearch }
    val MessageSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessageSquare }
    val MessageText by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessageText }
    val MessageTextOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessageTextOne }
    val MessageTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessageTick }
    val MessageTime by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessageTime }
    val MessageTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessageTwo }
    val Messages by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Messages }
    val MessagesOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessagesOne }
    val MessagesThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessagesThree }
    val MessagesTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MessagesTwo }
    val Messenger by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Messenger }
    val Microphone by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Microphone }
    val MicrophoneSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MicrophoneSlash }
    val MicrophoneSlashOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MicrophoneSlashOne }
    val MicrophoneTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MicrophoneTwo }
    val Microscope by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Microscope }
    val Milk by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Milk }
    val MiniMusicSqaure by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MiniMusicSqaure }
    val Minus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Minus }
    val MinusCirlce by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MinusCirlce }
    val MinusSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MinusSquare }
    val Mirror by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Mirror }
    val MirroringScreen by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MirroringScreen }
    val Mobile by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Mobile }
    val MobileProgramming by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MobileProgramming }
    val Monero by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Monero }
    val Money by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Money }
    val MoneyAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MoneyAdd }
    val MoneyArchive by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MoneyArchive }
    val MoneyChange by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MoneyChange }
    val MoneyForbidden by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MoneyForbidden }
    val MoneyFour by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MoneyFour }
    val MoneyRecive by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MoneyRecive }
    val MoneyRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MoneyRemove }
    val MoneySend by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MoneySend }
    val MoneyThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MoneyThree }
    val MoneyTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MoneyTick }
    val MoneyTime by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MoneyTime }
    val MoneyTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MoneyTwo }
    val Moneys by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Moneys }
    val Monitor by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Monitor }
    val MonitorMobbile by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MonitorMobbile }
    val MonitorRecorder by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MonitorRecorder }
    val Moon by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Moon }
    val More by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.More }
    val MoreCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MoreCircle }
    val MoreSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MoreSquare }
    val MoreTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MoreTwo }
    val Mouse by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Mouse }
    val MouseCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MouseCircle }
    val MouseSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MouseSquare }
    val Music by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Music }
    val MusicCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MusicCircle }
    val MusicDashboard by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MusicDashboard }
    val MusicFilter by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MusicFilter }
    val MusicLibraryTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MusicLibraryTwo }
    val MusicPlay by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MusicPlay }
    val MusicPlaylist by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MusicPlaylist }
    val MusicSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MusicSquare }
    val MusicSquareAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MusicSquareAdd }
    val MusicSquareRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MusicSquareRemove }
    val MusicSquareSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.MusicSquareSearch }
    val Musicnote by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Musicnote }
    val Nebulas by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Nebulas }
    val Nem by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Nem }
    val Nexo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Nexo }
    val Next by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Next }
    val Note by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Note }
    val NoteAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.NoteAdd }
    val NoteFavorite by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.NoteFavorite }
    val NoteOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.NoteOne }
    val NoteRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.NoteRemove }
    val NoteSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.NoteSquare }
    val NoteText by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.NoteText }
    val Notepad by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Notepad }
    val NotepadTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.NotepadTwo }
    val Notification by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Notification }
    val NotificationBing by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.NotificationBing }
    val NotificationCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.NotificationCircle }
    val NotificationFavorite by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.NotificationFavorite }
    val NotificationOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.NotificationOne }
    val NotificationStatus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.NotificationStatus }
    val OceanProtocol by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.OceanProtocol }
    val Okb by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Okb }
    val Okru by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Okru }
    val OmegaCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.OmegaCircle }
    val OmegaSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.OmegaSquare }
    val Ontology by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Ontology }
    val Paintbucket by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Paintbucket }
    val Paperclip by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Paperclip }
    val PaperclipTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PaperclipTwo }
    val PasswordCheck by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PasswordCheck }
    val PathTool by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PathTool }
    val PathToolSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PathToolSquare }
    val PathToolTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PathToolTwo }
    val Pause by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Pause }
    val PauseCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PauseCircle }
    val Paypal by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Paypal }
    val PenAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PenAdd }
    val PenClose by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PenClose }
    val PenRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PenRemove }
    val PenTool by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PenTool }
    val PenToolTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PenToolTwo }
    val People by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.People }
    val PercentageCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PercentageCircle }
    val PercentageSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PercentageSquare }
    val Personalcard by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Personalcard }
    val Pet by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Pet }
    val Pharagraphspacing by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Pharagraphspacing }
    val Photoshop by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Photoshop }
    val PictureFrame by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PictureFrame }
    val Play by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Play }
    val PlayAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PlayAdd }
    val PlayCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PlayCircle }
    val PlayCricle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PlayCricle }
    val PlayRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PlayRemove }
    val Pointer by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Pointer }
    val Polkadot by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Polkadot }
    val Polygon by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Polygon }
    val Polyswarm by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Polyswarm }
    val PresentionChart by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PresentionChart }
    val Previous by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Previous }
    val Printer by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Printer }
    val PrinterSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.PrinterSlash }
    val Profile by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Profile }
    val ProfileAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ProfileAdd }
    val ProfileCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ProfileCircle }
    val ProfileDelete by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ProfileDelete }
    val ProfileRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ProfileRemove }
    val ProfileTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ProfileTick }
    val ProfileTwouser by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ProfileTwouser }
    val ProgrammingArrow by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ProgrammingArrow }
    val ProgrammingArrows by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ProgrammingArrows }
    val Python by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Python }
    val Quant by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Quant }
    val QuoteDown by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.QuoteDown }
    val QuoteDownCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.QuoteDownCircle }
    val QuoteDownSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.QuoteDownSquare }
    val QuoteUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.QuoteUp }
    val QuoteUpCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.QuoteUpCircle }
    val QuoteUpSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.QuoteUpSquare }
    val Radar by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Radar }
    val RadarTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RadarTwo }
    val Radio by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Radio }
    val Ram by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Ram }
    val RamTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RamTwo }
    val Rank by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Rank }
    val Ranking by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Ranking }
    val Receipt by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Receipt }
    val ReceiptAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ReceiptAdd }
    val ReceiptDiscount by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ReceiptDiscount }
    val ReceiptDisscount by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ReceiptDisscount }
    val ReceiptEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ReceiptEdit }
    val ReceiptItem by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ReceiptItem }
    val ReceiptMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ReceiptMinus }
    val ReceiptOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ReceiptOne }
    val ReceiptSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ReceiptSearch }
    val ReceiptSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ReceiptSquare }
    val ReceiptText by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ReceiptText }
    val ReceiptTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ReceiptTwo }
    val ReceiptTwoOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ReceiptTwoOne }
    val Receive by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Receive }
    val ReceiveSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ReceiveSquare }
    val ReceiveSquareTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ReceiveSquareTwo }
    val Record by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Record }
    val RecordCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RecordCircle }
    val RecoveryConvert by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RecoveryConvert }
    val Refresh by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Refresh }
    val RefreshCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RefreshCircle }
    val RefreshLeftSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RefreshLeftSquare }
    val RefreshRightSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RefreshRightSquare }
    val RefreshSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RefreshSquare }
    val RefreshTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RefreshTwo }
    val Repeat by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Repeat }
    val RepeatCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RepeatCircle }
    val RepeateMusic by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RepeateMusic }
    val RepeateOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RepeateOne }
    val Reserve by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Reserve }
    val RotateLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RotateLeft }
    val RotateRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RotateRight }
    val RouteSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RouteSquare }
    val Routing by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Routing }
    val RoutingTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RoutingTwo }
    val RowHorizontal by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RowHorizontal }
    val RowVertical by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RowVertical }
    val Ruler by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Ruler }
    val RulerPen by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.RulerPen }
    val SafeHome by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SafeHome }
    val Sagittarius by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Sagittarius }
    val SaveAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SaveAdd }
    val SaveMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SaveMinus }
    val SaveRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SaveRemove }
    val SaveTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SaveTwo }
    val Scan by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Scan }
    val ScanBarcode by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ScanBarcode }
    val Scanner by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Scanner }
    val Scanning by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Scanning }
    val Scissor by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Scissor }
    val Screenmirroring by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Screenmirroring }
    val Scroll by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Scroll }
    val SearchFavorite by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SearchFavorite }
    val SearchFavoriteOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SearchFavoriteOne }
    val SearchNormal by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SearchNormal }
    val SearchNormalOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SearchNormalOne }
    val SearchStatus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SearchStatus }
    val SearchStatusOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SearchStatusOne }
    val SearchZoomIn by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SearchZoomIn }
    val SearchZoomInOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SearchZoomInOne }
    val SearchZoomOut by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SearchZoomOut }
    val SearchZoomOutOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SearchZoomOutOne }
    val Security by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Security }
    val SecurityCard by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SecurityCard }
    val SecuritySafe by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SecuritySafe }
    val SecurityTime by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SecurityTime }
    val SecurityUser by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SecurityUser }
    val Send by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Send }
    val SendTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SendTwo }
    val Setting by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Setting }
    val SettingFive by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SettingFive }
    val SettingFour by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SettingFour }
    val SettingThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SettingThree }
    val SettingTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SettingTwo }
    val Settings by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Settings }
    val Shapes by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Shapes }
    val ShapesOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ShapesOne }
    val Share by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Share }
    val Shield by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Shield }
    val ShieldCross by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ShieldCross }
    val ShieldSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ShieldSearch }
    val ShieldSecurity by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ShieldSecurity }
    val ShieldSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ShieldSlash }
    val ShieldTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ShieldTick }
    val Ship by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Ship }
    val Shop by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Shop }
    val ShopAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ShopAdd }
    val ShopRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ShopRemove }
    val ShoppingBag by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ShoppingBag }
    val ShoppingCart by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ShoppingCart }
    val Shuffle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Shuffle }
    val Shutterstock by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Shutterstock }
    val Siacoin by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Siacoin }
    val SidebarBottom by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SidebarBottom }
    val SidebarLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SidebarLeft }
    val SidebarRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SidebarRight }
    val SidebarTop by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SidebarTop }
    val Signpost by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Signpost }
    val Simcard by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Simcard }
    val SimcardOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SimcardOne }
    val SimcardTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SimcardTwo }
    val Size by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Size }
    val Slack by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Slack }
    val Slash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Slash }
    val Slider by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Slider }
    val SliderHorizontal by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SliderHorizontal }
    val SliderHorizontalOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SliderHorizontalOne }
    val SliderVertical by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SliderVertical }
    val SliderVerticalOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SliderVerticalOne }
    val Smallcaps by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Smallcaps }
    val SmartCar by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SmartCar }
    val SmartHome by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SmartHome }
    val Smileys by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Smileys }
    val Sms by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Sms }
    val SmsEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SmsEdit }
    val SmsNotification by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SmsNotification }
    val SmsSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SmsSearch }
    val SmsStar by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SmsStar }
    val SmsTracking by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SmsTracking }
    val Snapchat by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Snapchat }
    val Solana by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Solana }
    val Sort by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Sort }
    val Sound by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Sound }
    val Speaker by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Speaker }
    val Speedometer by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Speedometer }
    val Spotify by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Spotify }
    val Stacks by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Stacks }
    val Star by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Star }
    val StarOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.StarOne }
    val StarSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.StarSlash }
    val Status by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Status }
    val StatusUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.StatusUp }
    val Stellar by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Stellar }
    val Sticker by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Sticker }
    val Stickynote by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Stickynote }
    val Stop by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Stop }
    val StopCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.StopCircle }
    val Story by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Story }
    val Strongbox by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Strongbox }
    val StrongboxTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.StrongboxTwo }
    val Subtitle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Subtitle }
    val Sun by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Sun }
    val SunFog by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SunFog }
    val SunOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.SunOne }
    val TableDocument by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TableDocument }
    val TableLamp by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TableLamp }
    val Tag by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Tag }
    val TagCross by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TagCross }
    val TagRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TagRight }
    val TagTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TagTwo }
    val TagUser by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TagUser }
    val Task by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Task }
    val TaskSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TaskSquare }
    val Teacher by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Teacher }
    val Tenx by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Tenx }
    val Tether by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Tether }
    val Text by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Text }
    val TextBlock by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TextBlock }
    val TextBold by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TextBold }
    val TextItalic by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TextItalic }
    val TextUnderline by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TextUnderline }
    val TextalignCenter by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TextalignCenter }
    val TextalignJustifycenter by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TextalignJustifycenter }
    val TextalignJustifyleft by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TextalignJustifyleft }
    val TextalignJustifyright by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TextalignJustifyright }
    val TextalignLeft by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TextalignLeft }
    val TextalignRight by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TextalignRight }
    val TheGraph by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TheGraph }
    val Theta by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Theta }
    val Thorchain by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Thorchain }
    val ThreedCubeScan by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ThreedCubeScan }
    val ThreedRotate by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ThreedRotate }
    val ThreedSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ThreedSquare }
    val Threedcube by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Threedcube }
    val Threesquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Threesquare }
    val TickCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TickCircle }
    val TickSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TickSquare }
    val Ticket by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Ticket }
    val TicketDiscount by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TicketDiscount }
    val TicketExpired by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TicketExpired }
    val TicketStar by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TicketStar }
    val TicketTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TicketTwo }
    val Timer by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Timer }
    val TimerOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TimerOne }
    val TimerPause by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TimerPause }
    val TimerStart by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TimerStart }
    val ToggleOff by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ToggleOff }
    val ToggleOffCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ToggleOffCircle }
    val ToggleOn by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ToggleOn }
    val ToggleOnCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.ToggleOnCircle }
    val Trade by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Trade }
    val TransactionMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TransactionMinus }
    val Translate by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Translate }
    val Transmit by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Transmit }
    val TransmitSqaureTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TransmitSqaureTwo }
    val TransmitSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TransmitSquare }
    val Trash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Trash }
    val Tree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Tree }
    val Trello by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Trello }
    val TrendDown by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TrendDown }
    val TrendUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TrendUp }
    val Triangle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Triangle }
    val TriangleLogo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TriangleLogo }
    val Trontron by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Trontron }
    val Truck by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Truck }
    val TruckFast by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TruckFast }
    val TruckRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TruckRemove }
    val TruckTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TruckTick }
    val TruckTime by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TruckTime }
    val TrushSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TrushSquare }
    val TwentyFourSupport by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.TwentyFourSupport }
    val Twitch by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Twitch }
    val Uieight by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Uieight }
    val Unlimited by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Unlimited }
    val Unlock by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Unlock }
    val UsdCoin by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.UsdCoin }
    val User by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.User }
    val UserAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.UserAdd }
    val UserCirlceAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.UserCirlceAdd }
    val UserEdit by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.UserEdit }
    val UserMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.UserMinus }
    val UserOctagon by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.UserOctagon }
    val UserRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.UserRemove }
    val UserSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.UserSearch }
    val UserSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.UserSquare }
    val UserTag by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.UserTag }
    val UserTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.UserTick }
    val Velas by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Velas }
    val Verify by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Verify }
    val Vibe by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Vibe }
    val Video by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Video }
    val VideoAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VideoAdd }
    val VideoCircle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VideoCircle }
    val VideoHorizontal by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VideoHorizontal }
    val VideoOctagon by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VideoOctagon }
    val VideoPlay by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VideoPlay }
    val VideoRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VideoRemove }
    val VideoSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VideoSlash }
    val VideoSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VideoSquare }
    val VideoTick by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VideoTick }
    val VideoTime by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VideoTime }
    val VideoVertical by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VideoVertical }
    val VoiceCricle by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VoiceCricle }
    val VoiceSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VoiceSquare }
    val Volume by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Volume }
    val VolumeCross by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VolumeCross }
    val VolumeHigh by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VolumeHigh }
    val VolumeLow by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VolumeLow }
    val VolumeLowOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VolumeLowOne }
    val VolumeMute by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VolumeMute }
    val VolumeSlash by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VolumeSlash }
    val VolumeUp by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.VolumeUp }
    val Wallet by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Wallet }
    val WalletAdd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.WalletAdd }
    val WalletAddOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.WalletAddOne }
    val WalletCheck by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.WalletCheck }
    val WalletMinus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.WalletMinus }
    val WalletMoney by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.WalletMoney }
    val WalletOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.WalletOne }
    val WalletRemove by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.WalletRemove }
    val WalletSearch by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.WalletSearch }
    val WalletThree by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.WalletThree }
    val WalletTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.WalletTwo }
    val Wanchain by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Wanchain }
    val WanchainOne by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.WanchainOne }
    val WarningTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.WarningTwo }
    val Watch by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Watch }
    val WatchStatus by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.WatchStatus }
    val Weight by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Weight }
    val WeightMeter by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.WeightMeter }
    val Whatsapp by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Whatsapp }
    val Wifi by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Wifi }
    val WifiSquare by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.WifiSquare }
    val Wind by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Wind }
    val WindTwo by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.WindTwo }
    val Windows by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Windows }
    val Wing by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Wing }
    val Woman by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Woman }
    val WristClock by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.WristClock }
    val Xd by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Xd }
    val Xiaomi by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Xiaomi }
    val Xrp by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Xrp }
    val Youtube by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Youtube }
    val Zel by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Zel }
    val Zoom by lazy { com.github.yohannestz.iconsax_compose.iconsax.broken.Zoom }
}
