package com.github.yohannestz.iconsax_compose.iconsax.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val OceanProtocol: ImageVector
    get() {
        val current = _oceanProtocol
        if (current != null) return current

        return ImageVector.Builder(
            name = "com.github.yohannestz.iconsax_compose.iconsax.IconsaxTheme.OceanProtocol",
            defaultWidth = 24.0.dp,
            defaultHeight = 24.0.dp,
            viewportWidth = 24.0f,
            viewportHeight = 24.0f,
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000)),
            ) {
                moveTo(x = 12.0f, y = 4.75f)
                quadToRelative(dx1 = -0.15f, dy1 = 0.0f, dx2 = -0.29f, dy2 = -0.03f)
                lineToRelative(dx = -0.28f, dy = -0.08f)
                lineToRelative(dx = -0.26f, dy = -0.14f)
                arcToRelative(a = 1.5f, b = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.0f, dy1 = -2.5f)
                lineToRelative(dx = 0.26f, dy = -0.13f)
                lineToRelative(dx = 0.28f, dy = -0.09f)
                arcTo(horizontalEllipseRadius = 1.5f, verticalEllipseRadius = 1.5f, theta = 0.0f, isMoreThanHalf = true, isPositiveArc = true, x1 = 12.0f, y1 = 4.75f)
                moveToRelative(dx = 0.0f, dy = 4.5f)
                quadToRelative(dx1 = -0.15f, dy1 = 0.0f, dx2 = -0.29f, dy2 = -0.03f)
                lineToRelative(dx = -0.28f, dy = -0.08f)
                lineTo(x = 11.17f, y = 9.0f)
                lineToRelative(dx = -0.23f, dy = -0.19f)
                arcToRelative(a = 1.5f, b = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.23f, dy1 = -2.31f)
                lineToRelative(dx = 0.26f, dy = -0.13f)
                arcToRelative(a = 1.4f, b = 1.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 1.14f, dy1 = 0.0f)
                lineToRelative(dx = 0.26f, dy = 0.13f)
                arcToRelative(a = 1.5f, b = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.23f, dy1 = 2.31f)
                lineTo(x = 12.83f, y = 9.0f)
                lineToRelative(dx = -0.26f, dy = 0.14f)
                lineToRelative(dx = -0.28f, dy = 0.08f)
                close()
                moveToRelative(dx = 0.0f, dy = 4.0f)
                quadToRelative(dx1 = -0.15f, dy1 = 0.0f, dx2 = -0.29f, dy2 = -0.03f)
                lineToRelative(dx = -0.28f, dy = -0.08f)
                lineTo(x = 11.17f, y = 13.0f)
                lineToRelative(dx = -0.23f, dy = -0.19f)
                arcToRelative(a = 1.5f, b = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.41f, dy1 = -0.77f)
                arcToRelative(a = 1.5f, b = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.41f, dy1 = -1.35f)
                lineToRelative(dx = 0.23f, dy = -0.19f)
                lineToRelative(dx = 0.26f, dy = -0.14f)
                lineToRelative(dx = 0.28f, dy = -0.08f)
                arcToRelative(a = 1.5f, b = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 1.76f, dy1 = 1.76f)
                lineToRelative(dx = -0.09f, dy = 0.28f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.32f, dy1 = 0.49f)
                lineTo(x = 12.83f, y = 13.0f)
                lineToRelative(dx = -0.26f, dy = 0.14f)
                lineToRelative(dx = -0.28f, dy = 0.08f)
                close()
                moveToRelative(dx = 0.0f, dy = 3.5f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.71f, dy1 = -0.29f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.29f, dy1 = -0.7f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.29f, dy1 = -0.72f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 1.09f, dy1 = -0.2f)
                lineToRelative(dx = 0.17f, dy = 0.08f)
                lineToRelative(dx = 0.16f, dy = 0.12f)
                arcTo(horizontalEllipseRadius = 1.0f, verticalEllipseRadius = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 13.0f, y1 = 15.75f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.29f, dy1 = 0.71f)
                lineToRelative(dx = -0.16f, dy = 0.12f)
                lineToRelative(dx = -0.17f, dy = 0.1f)
                lineToRelative(dx = -0.19f, dy = 0.05f)
                close()
                moveTo(x = 12.0f, y = 20.0f)
                arcToRelative(a = 0.8f, b = 0.8f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.53f, dy1 = -0.22f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.16f, dy1 = -0.24f)
                arcTo(horizontalEllipseRadius = 0.75f, verticalEllipseRadius = 0.75f, theta = 0.0f, isMoreThanHalf = true, isPositiveArc = true, x1 = 12.0f, y1 = 20.0f)
                moveToRelative(dx = 0.0f, dy = 2.07f)
                arcToRelative(a = 0.5f, b = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.35f, dy1 = -0.15f)
                arcToRelative(a = 0.5f, b = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.15f, dy1 = -0.35f)
                arcToRelative(a = 0.5f, b = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 1.0f, dy1 = 0.0f)
                arcToRelative(a = 0.5f, b = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.15f, dy1 = 0.35f)
                arcToRelative(a = 0.5f, b = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.35f, dy1 = 0.15f)
                moveTo(x = 3.5f, y = 9.25f)
                arcToRelative(a = 1.5f, b = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -1.06f, dy1 = -2.56f)
                arcToRelative(a = 1.55f, b = 1.55f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 2.12f, dy1 = 0.0f)
                arcTo(horizontalEllipseRadius = 1.5f, verticalEllipseRadius = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 4.33f, y1 = 9.0f)
                lineTo(x = 4.07f, y = 9.13f)
                arcTo(horizontalEllipseRadius = 1.4f, verticalEllipseRadius = 1.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 3.5f, y1 = 9.25f)
                moveToRelative(dx = 17.0f, dy = 0.0f)
                curveToRelative(dx1 = -0.39f, dy1 = 0.0f, dx2 = -0.78f, dy2 = -0.16f, dx3 = -1.06f, dy3 = -0.44f)
                arcToRelative(a = 1.5f, b = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.41f, dy1 = -1.35f)
                lineToRelative(dx = 0.08f, dy = -0.28f)
                lineToRelative(dx = 0.14f, dy = -0.26f)
                lineToRelative(dx = 0.19f, dy = -0.23f)
                lineToRelative(dx = 0.23f, dy = -0.19f)
                lineToRelative(dx = 0.26f, dy = -0.13f)
                arcToRelative(a = 1.4f, b = 1.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 1.14f, dy1 = 0.0f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.49f, dy1 = 0.32f)
                lineToRelative(dx = 0.19f, dy = 0.23f)
                lineToRelative(dx = 0.13f, dy = 0.26f)
                arcTo(horizontalEllipseRadius = 1.4f, verticalEllipseRadius = 1.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 22.0f, y1 = 7.75f)
                arcTo(horizontalEllipseRadius = 1.5f, verticalEllipseRadius = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 21.33f, y1 = 9.0f)
                lineToRelative(dx = -0.26f, dy = 0.14f)
                lineToRelative(dx = -0.28f, dy = 0.08f)
                close()
                moveToRelative(dx = 0.0f, dy = 3.5f)
                lineToRelative(dx = -0.19f, dy = -0.02f)
                lineToRelative(dx = -0.19f, dy = -0.06f)
                lineToRelative(dx = -0.18f, dy = -0.1f)
                quadToRelative(dx1 = -0.08f, dy1 = -0.04f, dx2 = -0.15f, dy2 = -0.11f)
                lineToRelative(dx = -0.12f, dy = -0.15f)
                lineToRelative(dx = -0.09f, dy = -0.18f)
                lineToRelative(dx = -0.06f, dy = -0.18f)
                lineToRelative(dx = -0.02f, dy = -0.2f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.29f, dy1 = -0.71f)
                lineToRelative(dx = 0.15f, dy = -0.12f)
                lineToRelative(dx = 0.18f, dy = -0.1f)
                lineToRelative(dx = 0.19f, dy = -0.05f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.38f, dy1 = 0.0f)
                lineToRelative(dx = 0.19f, dy = 0.06f)
                lineToRelative(dx = 0.17f, dy = 0.09f)
                lineToRelative(dx = 0.16f, dy = 0.12f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.29f, dy1 = 0.7f)
                lineToRelative(dx = -0.02f, dy = 0.2f)
                lineToRelative(dx = -0.06f, dy = 0.19f)
                lineToRelative(dx = -0.09f, dy = 0.18f)
                lineToRelative(dx = -0.12f, dy = 0.15f)
                quadToRelative(dx1 = -0.07f, dy1 = 0.07f, dx2 = -0.16f, dy2 = 0.12f)
                lineToRelative(dx = -0.17f, dy = 0.09f)
                lineToRelative(dx = -0.19f, dy = 0.06f)
                close()
                moveToRelative(dx = -17.0f, dy = 0.0f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.71f, dy1 = -0.3f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.29f, dy1 = -0.7f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.29f, dy1 = -0.71f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 1.09f, dy1 = -0.21f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.33f, dy1 = 0.2f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.29f, dy1 = 0.72f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.29f, dy1 = 0.7f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.71f, dy1 = 0.3f)
                moveToRelative(dx = 17.0f, dy = 2.75f)
                arcToRelative(a = 0.75f, b = 0.75f, theta = 0.0f, isMoreThanHalf = true, isPositiveArc = true, dx1 = 0.0f, dy1 = -1.5f)
                arcToRelative(a = 0.75f, b = 0.75f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.0f, dy1 = 1.5f)
                moveToRelative(dx = -17.0f, dy = 0.0f)
                arcToRelative(a = 0.75f, b = 0.75f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.69f, dy1 = -1.04f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.16f, dy1 = -0.24f)
                arcToRelative(a = 0.77f, b = 0.77f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 1.06f, dy1 = 0.0f)
                arcToRelative(a = 0.8f, b = 0.8f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.22f, dy1 = 0.53f)
                arcToRelative(a = 0.8f, b = 0.8f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.22f, dy1 = 0.53f)
                arcToRelative(a = 0.8f, b = 0.8f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.53f, dy1 = 0.22f)
                moveToRelative(dx = 17.0f, dy = 2.5f)
                arcToRelative(a = 0.4f, b = 0.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.19f, dy1 = -0.04f)
                arcToRelative(a = 0.4f, b = 0.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.16f, dy1 = -0.11f)
                arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 20.0f, y1 = 17.5f)
                arcToRelative(a = 0.5f, b = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 1.0f, dy1 = 0.0f)
                arcToRelative(a = 0.5f, b = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.15f, dy1 = 0.35f)
                arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 20.5f, y1 = 18.0f)
                moveToRelative(dx = -17.0f, dy = 0.0f)
                arcToRelative(a = 0.5f, b = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.35f, dy1 = -0.15f)
                arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 3.0f, y1 = 17.5f)
                arcToRelative(a = 0.5f, b = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 1.0f, dy1 = 0.0f)
                arcToRelative(a = 0.5f, b = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.15f, dy1 = 0.35f)
                arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 3.5f, y1 = 18.0f)
                moveTo(x = 7.75f, y = 7.0f)
                arcToRelative(a = 1.4f, b = 1.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.57f, dy1 = -0.12f)
                quadTo(x1 = 7.04f, y1 = 6.83f, x2 = 6.92f, y2 = 6.75f)
                arcTo(horizontalEllipseRadius = 1.5f, verticalEllipseRadius = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 6.25f, y1 = 5.5f)
                arcToRelative(a = 1.5f, b = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.44f, dy1 = -1.06f)
                arcToRelative(a = 1.55f, b = 1.55f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 2.12f, dy1 = 0.0f)
                arcToRelative(a = 1.5f, b = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.23f, dy1 = 2.31f)
                lineTo(x = 8.32f, y = 6.88f)
                arcTo(horizontalEllipseRadius = 1.4f, verticalEllipseRadius = 1.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 7.75f, y1 = 7.0f)
                moveToRelative(dx = 8.5f, dy = 0.0f)
                arcToRelative(a = 1.4f, b = 1.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.57f, dy1 = -0.12f)
                lineToRelative(dx = -0.26f, dy = -0.13f)
                lineToRelative(dx = -0.23f, dy = -0.19f)
                lineTo(x = 15.0f, y = 6.33f)
                lineToRelative(dx = -0.14f, dy = -0.26f)
                lineToRelative(dx = -0.08f, dy = -0.28f)
                lineToRelative(dx = -0.03f, dy = -0.29f)
                arcToRelative(a = 1.5f, b = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.67f, dy1 = -1.25f)
                lineToRelative(dx = 0.26f, dy = -0.13f)
                arcToRelative(a = 1.4f, b = 1.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 1.14f, dy1 = 0.0f)
                lineToRelative(dx = 0.26f, dy = 0.13f)
                arcToRelative(a = 1.5f, b = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.67f, dy1 = 1.25f)
                quadToRelative(dx1 = 0.0f, dy1 = 0.15f, dx2 = -0.03f, dy2 = 0.29f)
                lineToRelative(dx = -0.08f, dy = 0.28f)
                lineToRelative(dx = -0.14f, dy = 0.26f)
                lineToRelative(dx = -0.19f, dy = 0.23f)
                lineToRelative(dx = -0.23f, dy = 0.19f)
                lineToRelative(dx = -0.26f, dy = 0.13f)
                arcTo(horizontalEllipseRadius = 1.4f, verticalEllipseRadius = 1.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 16.25f, y1 = 7.0f)
                moveToRelative(dx = -8.5f, dy = 4.25f)
                quadToRelative(dx1 = -0.15f, dy1 = 0.0f, dx2 = -0.29f, dy2 = -0.03f)
                lineToRelative(dx = -0.28f, dy = -0.08f)
                arcToRelative(a = 2.0f, b = 2.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.49f, dy1 = -0.33f)
                arcToRelative(a = 1.5f, b = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.0f, dy1 = -2.12f)
                arcToRelative(a = 1.55f, b = 1.55f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 2.12f, dy1 = 0.0f)
                arcToRelative(a = 1.5f, b = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -1.06f, dy1 = 2.56f)
                moveToRelative(dx = 8.5f, dy = 0.0f)
                arcToRelative(a = 1.4f, b = 1.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.57f, dy1 = -0.12f)
                lineTo(x = 15.42f, y = 11.0f)
                lineToRelative(dx = -0.23f, dy = -0.19f)
                lineTo(x = 15.0f, y = 10.58f)
                lineToRelative(dx = -0.14f, dy = -0.26f)
                lineToRelative(dx = -0.08f, dy = -0.28f)
                lineToRelative(dx = -0.03f, dy = -0.29f)
                arcToRelative(a = 1.5f, b = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.67f, dy1 = -1.25f)
                lineToRelative(dx = 0.26f, dy = -0.13f)
                arcToRelative(a = 1.4f, b = 1.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 1.14f, dy1 = 0.0f)
                lineToRelative(dx = 0.26f, dy = 0.13f)
                arcToRelative(a = 1.5f, b = 1.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.67f, dy1 = 1.25f)
                quadToRelative(dx1 = 0.0f, dy1 = 0.15f, dx2 = -0.03f, dy2 = 0.29f)
                lineToRelative(dx = -0.08f, dy = 0.28f)
                lineToRelative(dx = -0.14f, dy = 0.26f)
                lineToRelative(dx = -0.19f, dy = 0.23f)
                lineTo(x = 17.08f, y = 11.0f)
                lineToRelative(dx = -0.26f, dy = 0.13f)
                arcToRelative(a = 1.4f, b = 1.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.57f, dy1 = 0.12f)
                moveToRelative(dx = -8.5f, dy = 3.5f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.38f, dy1 = -0.08f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.33f, dy1 = -0.21f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.21f, dy1 = -0.33f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.08f, dy1 = -0.38f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.29f, dy1 = -0.71f)
                arcToRelative(a = 1.05f, b = 1.05f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 1.42f, dy1 = 0.0f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.29f, dy1 = 0.71f)
                quadToRelative(dx1 = 0.0f, dy1 = 0.2f, dx2 = -0.08f, dy2 = 0.38f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.21f, dy1 = 0.33f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.71f, dy1 = 0.29f)
                moveToRelative(dx = 8.5f, dy = 0.0f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.71f, dy1 = -0.29f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.29f, dy1 = -0.71f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.29f, dy1 = -0.71f)
                arcToRelative(a = 1.05f, b = 1.05f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 1.42f, dy1 = 0.0f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.29f, dy1 = 0.71f)
                lineToRelative(dx = -0.02f, dy = 0.2f)
                lineToRelative(dx = -0.06f, dy = 0.18f)
                lineToRelative(dx = -0.09f, dy = 0.17f)
                lineToRelative(dx = -0.12f, dy = 0.16f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.71f, dy1 = 0.29f)
                moveToRelative(dx = -8.5f, dy = 3.0f)
                arcToRelative(a = 0.75f, b = 0.75f, theta = 0.0f, isMoreThanHalf = true, isPositiveArc = true, dx1 = 0.0f, dy1 = -1.5f)
                arcToRelative(a = 0.75f, b = 0.75f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.0f, dy1 = 1.5f)
                moveToRelative(dx = 8.5f, dy = 0.0f)
                arcToRelative(a = 0.8f, b = 0.8f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.53f, dy1 = -0.22f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.16f, dy1 = -0.24f)
                arcToRelative(a = 0.7f, b = 0.7f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.0f, dy1 = -0.58f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.16f, dy1 = -0.24f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.24f, dy1 = -0.16f)
                arcToRelative(a = 0.7f, b = 0.7f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.58f, dy1 = 0.0f)
                arcToRelative(a = 1.0f, b = 1.0f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 0.24f, dy1 = 0.16f)
                arcTo(horizontalEllipseRadius = 0.8f, verticalEllipseRadius = 0.8f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 17.0f, y1 = 17.0f)
                arcToRelative(a = 0.8f, b = 0.8f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.22f, dy1 = 0.53f)
                arcToRelative(a = 0.8f, b = 0.8f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.53f, dy1 = 0.22f)
                moveTo(x = 7.75f, y = 20.0f)
                arcToRelative(a = 0.5f, b = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.35f, dy1 = -0.15f)
                arcToRelative(a = 0.5f, b = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.15f, dy1 = -0.35f)
                arcToRelative(a = 0.5f, b = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 1.0f, dy1 = 0.0f)
                arcToRelative(a = 0.5f, b = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.15f, dy1 = 0.35f)
                arcTo(horizontalEllipseRadius = 0.5f, verticalEllipseRadius = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, x1 = 7.75f, y1 = 20.0f)
                moveToRelative(dx = 8.5f, dy = 0.0f)
                arcToRelative(a = 0.4f, b = 0.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.19f, dy1 = -0.04f)
                arcToRelative(a = 0.4f, b = 0.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.16f, dy1 = -0.11f)
                arcToRelative(a = 0.4f, b = 0.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.11f, dy1 = -0.16f)
                arcToRelative(a = 0.4f, b = 0.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.04f, dy1 = -0.19f)
                arcToRelative(a = 0.5f, b = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = 1.0f, dy1 = 0.0f)
                arcToRelative(a = 0.4f, b = 0.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.04f, dy1 = 0.19f)
                arcToRelative(a = 0.4f, b = 0.4f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.11f, dy1 = 0.16f)
                arcToRelative(a = 0.5f, b = 0.5f, theta = 0.0f, isMoreThanHalf = false, isPositiveArc = true, dx1 = -0.35f, dy1 = 0.15f)
            }
        }.build().also { _oceanProtocol = it }
    }

@Suppress("ObjectPropertyName")
private var _oceanProtocol: ImageVector? = null
